/*
 * This source file was generated by the Gradle 'init' task
 */
package linked.list;

public class App {
    public static void main(String[] args) {
        LinkedList list = new LinkedList();
        list.tambahDepan(20);
        list.tambahDepan(10);
        list.cetak();

        list.tambahBelakang(30);
        list.tambahBelakang(40);
        list.cetak();

        System.out.println("Mencari data 30: " + (list.cari(30) ? "Ditemukan" : "Tidak ditemukan"));
        
        list.hapus(20);
        list.cetak();
        
        list.hapus(10);
        list.cetak();
        
        System.out.println("Mencari data 50: " + (list.cari(50) ? "Ditemukan" : "Tidak ditemukan"));

    }
}


